In [2]:
import numpy as np
import pandas as pd

df1 = pd.read_csv('各鄉鎮市區人口密度.csv')
df1

,statistic_yyy,site_id,people_total,area,population_density
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [4]:
df1.index
df1.columns

Index(['statistic_yyy', 'site_id', 'people_total', 'area',
       'population_density'],
      dtype='object')

In [9]:
df1.columns = df1.iloc[0].values.tolist()
df2 = df1.drop(index=[0])
df2

,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
5,106,新北市新莊區,416524,19.7383,21102
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 1 to 375
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     374 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: object(5)
memory usage: 14.8+ KB

In [14]:
df3 = df2.dropna()
df3

     統計年     區域別   年底人口數     土地面積   人口密度
1    106  新北市板橋區  551480  23.1373  23835
2    106  新北市三重區  387484   16.317  23747
3    106  新北市中和區  413590   20.144  20532
4    106  新北市永和區  222585   5.7138  38956
5    106  新北市新莊區  416524  19.7383  21102
..   ...     ...     ...      ...    ...
366  106  連江縣北竿鄉    2360      9.9    238
367  106  連江縣莒光鄉    1624      4.7    346
368  106  連江縣東引鄉    1352      3.8    356
369  106    東沙群島      …      2.38     …
370  106    南沙群島      …    0.5045     …

[370 rows x 5 columns]

In [16]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: object(5)
memory usage: 17.3+ KB

In [23]:
df3.loc[:,'土地面積'] = df3['土地面積'].astype(float)
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    float64
 4   人口密度    370 non-null    object
dtypes: float64(1), object(4)
memory usage: 17.3+ KB

In [24]:
df3.loc[:,'年底人口數'] = df3['年底人口數'].astype(int)

ValueError: invalid literal for int() with base 10: '… '