In [2]:
import numpy as np
import pandas as pd

scores = pd.DataFrame(np.random.randint(50,101,size=(50,5)),
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores

    國文  英文   數學   地理  歷史
1   60  71   58   95  84
2   76  56   86   90  72
3   75  66   97   84  90
4   77  82   83   76  82
5   79  56   84   73  78
6   92  83   68   53  75
7   63  83   69  100  68
8   97  96   95   95  81
9   94  60   74   78  64
10  63  84   72   85  68
11  67  79   65   50  91
12  74  73   83   61  72
13  87  73   59   76  76
14  83  87   91   68  57
15  72  73   66   97  75
16  79  75   81   73  92
17  52  55   87   97  66
18  92  69   66   62  84
19  50  80   74   74  76
20  78  50   94   82  81
21  70  95   71   59  53
22  65  69   68   70  88
23  82  62   60   72  87
24  99  63   79   71  93
25  97  81   62   62  65
26  55  88   94   52  93
27  84  61   87   96  61
28  87  84   78   60  77
29  63  80   89   77  75
30  50  72   78   83  91
31  68  60   95   69  98
32  55  66   86   65  68
33  82  86   62   57  82
34  89  63   67   75  58
35  88  52   55   94  62
36  62  86   56   93  76
37  86  61   50   86  82
38  58  92   50   80  68
39  53  70   74   51  69
40  60  57   99   99  61
41  61  98   70   69  97
42  84  88   55   71  84
43  64  58   84   90  50
44  93  92   66   71  53
45  87  91  100   55  91
46  95  98   51   87  79
47  80  68   85   93  88
48  56  98   70   57  79
49  89  68   86   90  56
50  55  51   74   96  64

In [6]:
def abc(s):
    return s.max()
scores.apply(abc)

國文     99
英文     98
數學    100
地理    100
歷史     98
dtype: int64

In [7]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()],index=['最低分','最高分','平均'])
scores.apply(abc)

        國文     英文      數學      地理    歷史
最低分  50.00  50.00   50.00   50.00  50.0
最高分  99.00  98.00  100.00  100.00  98.0
平均   74.54  74.18   75.06   76.38  75.6

In [ ]:

scores.index = scores.index.map(lambda i:f'{i}號')
scores

In [13]:
def abc1(item):
    return pd.Series([item.sum(),item.mean()],index=['總分','平均'])
scores.apply(abc1,axis=1)

        總分    平均
1號   368.0  73.6
2號   380.0  76.0
3號   412.0  82.4
4號   400.0  80.0
5號   370.0  74.0
6號   371.0  74.2
7號   383.0  76.6
8號   464.0  92.8
9號   370.0  74.0
10號  372.0  74.4
11號  352.0  70.4
12號  363.0  72.6
13號  371.0  74.2
14號  386.0  77.2
15號  383.0  76.6
16號  400.0  80.0
17號  357.0  71.4
18號  373.0  74.6
19號  354.0  70.8
20號  385.0  77.0
21號  348.0  69.6
22號  360.0  72.0
23號  363.0  72.6
24號  405.0  81.0
25號  367.0  73.4
26號  382.0  76.4
27號  389.0  77.8
28號  386.0  77.2
29號  384.0  76.8
30號  374.0  74.8
31號  390.0  78.0
32號  340.0  68.0
33號  369.0  73.8
34號  352.0  70.4
35號  351.0  70.2
36號  373.0  74.6
37號  365.0  73.0
38號  348.0  69.6
39號  317.0  63.4
40號  376.0  75.2
41號  395.0  79.0
42號  382.0  76.4
43號  346.0  69.2
44號  375.0  75.0
45號  424.0  84.8
46號  410.0  82.0
47號  414.0  82.8
48號  360.0  72.0
49號  389.0  77.8
50號  340.0  68.0